from data_trials.component.training.data_ingestion import DataIngestion
from data_trials.component.training.data_validation import DataValidation
from data_trials.component.training.data_transformation import DataTransformation
from data_trials.component.training.model_trainer import ModelTrainer
from data_trials.component.training.model_evaluation import ModelEvaluation
from data_trials.component.training.model_pusher import ModelPusher

